---
title: "data_transformation"
author: "Group"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
# Default knitting options
knitr::opts_chunk$set(echo=TRUE, # Echo the code
                      tidy=TRUE, # Nicely dity up code
                      warning=FALSE, # No warnings please 
                      message=FALSE) # No messages please

options(warn=-1) 

# Suppress start up warnings when loading libraries
library <- function(...) {
  suppressPackageStartupMessages(base::library(...))
}
```

```{r libraries}
# Load in all libraries
library(tidyverse)
library(here)      # directory referencing
library(readxl)    # reading Excel files
library(janitor)   # data cleaning 
library(stringr)   # string manimpuationf
library(tidyr)     # new tidy functions
```


```{r}


load(file = here("data", "tech_data.Rdata"))

aboriginal_cohort <- read_csv(file = here("data", "aboriginal_cohort.csv"))

tech_nutr_by_person_joined = 
  tech_nutr %>% 
  inner_join(tech_biom, by = "ABSPID") %>% 
  filter(!is.na(LDLNTR),
         AGEC >= 18) %>% 
  mutate(data_source = 'AHS',
         WHOLGR1N_PROP = WHOLGR1N/GRAINS1N)

aboriginal_cohort_filtered =
  aboriginal_cohort %>% 
  filter(AGEEC >= 18,
         LDLNTR %in% c(1,2)) %>% 
  rename(AGEC = AGEEC) %>% 
  mutate(data_source = 'Aboriginal',
         WHOLGR1N_PROP = WHOLGR1N/GRAINS1N)

required_columns <- c(
            'data_source',
            'LDLNTR',
            'WHOLGR1N',
            'WHOLGR1N_PROP',
            'REFGRA1N',
            'SYSTOL',
            'SLPTIME',
            'BMISC',
            'AGEC')

merged_data <- 
  tech_nutr_by_person_joined %>% 
  select(required_columns) %>% 
  rbind(select(aboriginal_cohort_filtered, required_columns)) %>% 
  mutate(LDLNTR = droplevels(LDLNTR))

merged_data %>% drop_na() %>% nrow


merged_data %>% 
  ggplot(aes(x = AGEC, col = data_source)) +
  geom_density()


merged_data %>% 
  ggplot(aes(x = WHOLGR1N, col = data_source)) +
  geom_density()

merged_data %>% 
  ggplot(aes(x = WHOLGR1N_PROP, col = data_source)) +
  geom_density()

model_2 <- glm(LDLNTR ~ WHOLGR1N_PROP + BMISC + AGEC + SLPTIME + SYSTOL, family = "binomial", data = merged_data)
summary(model_2)


merged_data %>% 
  ggplot(aes(x = LDLNTR, col = data_source)) +
  geom_density()

```


## Glucose

```{r}


tech_nutr_by_person_joined_glucose = 
  tech_nutr %>% 
  inner_join(tech_biom, by = "ABSPID") %>% 
  filter(!is.na(GLUCFPD),
         AGEC >= 18) %>% 
  mutate(data_source = 'AHS',
         WHOLGR1N_PROP = WHOLGR1N/GRAINS1N)

aboriginal_cohort_filtered_glucose =
  aboriginal_cohort %>% 
  filter(AGEEC >= 18,
         GLUCFPD %in% c(1,2,3)) %>% 
  rename(AGEC = AGEEC) %>% 
  mutate(data_source = 'Aboriginal',
         WHOLGR1N_PROP = WHOLGR1N/GRAINS1N)

required_columns_glucose <- c(
            'data_source',
            'GLUCFPD',
            'WHOLGR1N',
            'WHOLGR1N_PROP',
            'REFGRA1N',
            'SYSTOL',
            'SLPTIME',
            'BMISC',
            'AGEC')

merged_data_glucose <- 
  tech_nutr_by_person_joined_glucose %>% 
  select(required_columns) %>% 
  rbind(select(aboriginal_cohort_filtered_glucose, required_columns_glucose)) %>% 
  mutate(GLUCFPD = droplevels(GLUCFPD))




merged_data_glucose %>% 
  count(data_source, GLUCFPD) 

```

