---
title: "data_transformation"
author: "Group"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
# Default knitting options
knitr::opts_chunk$set(echo=TRUE, # Echo the code
                      tidy=TRUE, # Nicely dity up code
                      warning=FALSE, # No warnings please 
                      message=FALSE) # No messages please

options(warn=-1) 

# Suppress start up warnings when loading libraries
library <- function(...) {
  suppressPackageStartupMessages(base::library(...))
}
```

```{r libraries}
# Load in all libraries
library(tidyverse)
library(here)      # directory referencing
library(readxl)    # reading Excel files
library(janitor)   # data cleaning 
library(stringr)   # string manimpuationf
library(tidyr)
library(MASS)
```


```{r}
load(file = "tech_data.Rdata")

raw_biom <-  read_csv(file = here("data", "AHS11biomedical.csv"))

aboriginal_cohort <- read_csv(file = here("data", "aboriginal_cohort.csv"))

tech_nutr_by_person_joined = 
  tech_nutr %>% 
  inner_join(tech_biom, by = "ABSPID") %>% 
  filter(!is.na(LDLNTR),
         AGEC >= 18) %>% 
  mutate(data_source = 'AHS',
         WHOLGR1N_PROP = WHOLGR1N/GRAINS1N)

aboriginal_cohort_filtered =
  aboriginal_cohort %>% 
  filter(AGEEC >= 18,
         LDLNTR %in% c(1,2)) %>% 
  rename(AGEC = AGEEC) %>% 
  mutate(data_source = 'Aboriginal',
         WHOLGR1N_PROP = WHOLGR1N/GRAINS1N)

required_columns <- c(
            'data_source',
            'LDLNTR',
            'LDLRESB',
            'WHOLGR1N',
            'WHOLGR1N_PROP',
            'REFGRA1N',
            'SYSTOL',
            'SLPTIME',
            'BMISC',
            'AGEC',
            'EIBMR1',
            'HDLCHREB',
            'CHOLRESB',
            'TRIGRESB')

merged_data <- tech_nutr_by_person_joined[, required_columns]

merged_data <- rbind(merged_data, aboriginal_cohort_filtered[, required_columns])

merged_data$LDLNTR <- droplevels(merged_data$LDLNTR)

merged_data <- merged_data %>% drop_na()


merged_data %>% 
  ggplot(aes(x = AGEC, col = data_source)) +
  geom_density()

merged_data <- merged_data %>% 
  mutate(below_goldberg = EIBMR1 < 0.9)

merged_data %>% 
  group_by(data_source) %>% 
  summarise(num_goldberg_dropped = sum(below_goldberg),
            num_total = n(),
            goldberg_dropped_pct = num_goldberg_dropped/num_total)



merged_data %>% 
  ggplot(aes(x = WHOLGR1N, col = data_source)) +
  geom_density()

merged_data %>% 
  ggplot(aes(x = WHOLGR1N_PROP, col = data_source)) +
  geom_density()

model_2 <- glm(LDLNTR ~ WHOLGR1N_PROP + BMISC + AGEC + SLPTIME + SYSTOL, family = "binomial", data = merged_data)
summary(model_2)


merged_data %>% 
  ggplot(aes(x = LDLNTR, col = data_source)) +
  geom_density()
```


## Glucose

```{r}
tech_nutr_by_person_joined_glucose = 
  tech_nutr %>% 
  inner_join(tech_biom, by = "ABSPID") %>% 
  filter(!is.na(GLUCFPD),
         AGEC >= 18) %>% 
  mutate(data_source = 'AHS',
         WHOLGR1N_PROP = WHOLGR1N/GRAINS1N)

aboriginal_cohort_filtered_glucose =
  aboriginal_cohort %>% 
  filter(AGEEC >= 18,
         GLUCFPD %in% c(1,2,3)) %>% 
  rename(AGEC = AGEEC) %>% 
  mutate(data_source = 'Aboriginal',
         WHOLGR1N_PROP = WHOLGR1N/GRAINS1N)

required_columns_glucose <- c(
            'data_source',
            'GLUCFPD',
            'WHOLGR1N',
            'WHOLGR1N_PROP',
            'REFGRA1N',
            'SYSTOL',
            'SLPTIME',
            'BMISC',
            'AGEC')

merged_data_glucose <- tech_nutr_by_person_joined_glucose[, required_columns_glucose]

merged_data_glucose <- rbind(merged_data_glucose, aboriginal_cohort_filtered_glucose[, required_columns_glucose])

merged_data_glucose$GLUCFPD <- droplevels(merged_data_glucose$GLUCFPD)

merged_data_glucose %>% 
  count(data_source, GLUCFPD) 
```



```{r}
# ordinal on LDLRESB

model_3 <- polr(LDLRESB ~ WHOLGR1N_PROP + BMISC + AGEC + SLPTIME + SYSTOL, data = merged_data)
summary(model_3)
ctable <- coef(summary(model_3))
p <- pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
ctable <- cbind(ctable, "p value" = p)
ctable
```



```{r}
model_4 <- polr(LDLNTR ~ WHOLGR1N_PROP + BMISC + AGEC + SLPTIME + SYSTOL, data = merged_data, Hess=TRUE)
summary(model_4)
ctable <- coef(summary(model_4))
p <- pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
ctable <- cbind(ctable, "p value" = p)
ctable
```



```{r}
# multinomial 
model_5 <- multinom(LDLRESB ~ WHOLGR1N_PROP + BMISC + AGEC + SLPTIME + SYSTOL, data = merged_data, trace=FALSE)
summary(model_5)
```


```{r}
zvalues <- summary(model_5)$coefficients / summary(model_5)$standard.errors

# calculate p-values
pnorm(abs(zvalues), lower.tail=FALSE)*2
```


```{r}
# multinomial on LDLNTR

model_6 <- multinom(LDLNTR ~ WHOLGR1N_PROP + BMISC + AGEC + SLPTIME + SYSTOL, data = merged_data, trace=FALSE)
summary(model_6)
```


```{r}
zvalues <- summary(model_6)$coefficients / summary(model_6)$standard.errors

# calculate p-values
pnorm(abs(zvalues), lower.tail=FALSE)*2
```

