---
title: "Model Outputs (used for presentation etc)"
author: "Group"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
# Default knitting options
knitr::opts_chunk$set(echo=FALSE, # Whether to echo the code
                      # tidy=TRUE, # Nicely tidy up code
                      warning=FALSE, # No warnings please 
                      message=FALSE) # No messages please

options(warn=-1) 

# Suppress start up warnings when loading libraries
library <- function(...) {
  suppressPackageStartupMessages(base::library(...))
}
```

```{r libraries}
# Suppress start up warnings when loading libraries
library <- function(...) {
  suppressPackageStartupMessages(base::library(...))
}
# Load in all libraries
library(tidyverse)
library(here) # directory referencing
library(MASS)
library(nnet)
library(caret)
library(stargazer) # used by John for nice display of model output
library(knitr) # used for nice display of tables
library(pROC)
library(rms)
library(vcd)
library(boot)
```


```{r load data}
load(file = here("data", "model_data.Rdata"))
load(file = "models.Rdata")
```


### GLMs

#### LDL

```{r,results="asis", eval=TRUE, echo=FALSE}
coef(summary(glm_LDL)) %>%
  as_tibble(rownames = "Variable") %>%
  rename("p Value" = "Pr(>|z|)",
         "Z Value" = "z value") %>%
  kable(digits = c(0, 3, 3, 3, 3), format = "pipe", caption = "GLM on LDL_status")
```

#### HDL

```{r,results="asis", eval=TRUE, echo=FALSE}
coef(summary(glm_HDL)) %>%
  as_tibble(rownames = "Variable") %>%
  rename("p Value" = "Pr(>|z|)",
         "Z Value" = "z value") %>%
  kable(digits = c(0, 3, 3, 2, 2), format = "pipe", caption = "GLM on HDL_status")
```

#### Total Cholesterol

```{r,results="asis", eval=TRUE, echo=FALSE}
coef(summary(glm_CHOL)) %>%
  as_tibble(rownames = "Variable") %>%
  rename("p Value" = "Pr(>|z|)",
         "Z Value" = "z value") %>%
  kable(digits = c(0, 3, 3, 2, 2), format = "pipe", caption = "GLM on total_cholesterol_status")
```


### Ordinal Regressions

#### LDL
```{r,results="asis", eval=TRUE, echo=FALSE}
ctable <- coef(summary(ordinal_LDL))
p <- pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
ctable <- cbind(ctable, "p Value" = p)

ctable %>% as_tibble(rownames = "Variable") %>%
  rename("t Value" = "t value",
         "Estimate" = "Value") %>%
  kable(digits = c(0, 3, 3, 2, 2), format = "pipe", caption = "Ordinal on LDL")
```

####HDL
```{r,results="asis", eval=TRUE, echo=FALSE}
ctable <- coef(summary(ordinal_HDL))
p <- pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
ctable <- cbind(ctable, "p Value" = p)

ctable %>% as_tibble(rownames = "Variable") %>%
  rename("t Value" = "t value",
         "Estimate" = "Value") %>%
  kable(digits = c(0, 3, 3, 2, 2), format = "pipe", caption = "Ordinal on HDL")
```

#### Total Cholesterol
```{r,results="asis", eval=TRUE, echo=FALSE}
ctable <- coef(summary(ordinal_CHOL))
p <- pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
ctable <- cbind(ctable, "p Value" = p)

ctable %>% as_tibble(rownames = "Variable") %>%
  rename("t Value" = "t value",
         "Estimate" = "Value") %>%
  kable(digits = c(0, 3, 3, 2, 2), format = "pipe", caption = "Ordinal on total_cholesterol")
```

## Multinomial Regressions

#### LDL
```{r}
coef(summary(multinom_LDL)) %>% 
  as_tibble(rownames = "LDL_band") %>% 
  kable(digits = 3, format="pipe", caption = "Estimates")

# calculate p-values
zvalues <- summary(multinom_LDL)$coefficients / summary(multinom_LDL)$standard.errors
pvalues <- pnorm(abs(zvalues), lower.tail=FALSE)*2

pvalues %>%  
  as_tibble(rownames = "LDL_band") %>% 
  kable(digits = 2, format="pipe", caption = "p Values")

```

#### HDL
```{r}
coef(summary(multinom_HDL)) %>% 
  as_tibble(rownames = "HDL_band") %>% 
  kable(digits = 3, format="pipe", caption = "Estimates")

# calculate p-values
zvalues <- summary(multinom_HDL)$coefficients / summary(multinom_HDL)$standard.errors
pvalues <- pnorm(abs(zvalues), lower.tail=FALSE)*2

pvalues %>%  
  as_tibble(rownames = "HDL_band") %>% 
  kable(digits = 2, format="pipe", caption = "p Values")

```

#### Total Cholesterol
```{r}
coef(summary(multinom_CHOL)) %>% 
  as_tibble(rownames = "total_cholesterol_band") %>% 
  kable(digits = 3, format="pipe", caption = "Estimates")

# calculate p-values
zvalues <- summary(multinom_CHOL)$coefficients / summary(multinom_CHOL)$standard.errors
pvalues <- pnorm(abs(zvalues), lower.tail=FALSE)*2

pvalues %>%  
  as_tibble(rownames = "total_cholesterol_band") %>% 
  kable(digits = 2, format="pipe", caption = "p Values")

```

#ROC FOR GLM
```{r}
predicted_probabilities <- predict(glm_LDL, type = "response")
roc_data <- roc(model_data$LDL_status, predicted_probabilities)
plot(roc_data, main = "ROC Curve", col = "blue")
auc_score <- auc(roc_data)
print(paste("AUC:", auc_score))
```

```{r}
#5 highest leverage points
plot(glm_LDL,which=4,id.n=5)
```

#EValuation for Ordinal Regression
```{r}
summary(ordinal_LDL)
summary(ordinal_HDL)
summary(ordinal_CHOL)

```






