---
title: "Modelling Code"
author: "Group"
date: "`r Sys.Date()`"
output: html_document
---

```{r libraries}
# Load in all libraries
library(tidyverse)
library(here) # directory referencing
library(MASS)
library(nnet)
library(randomForest)
library(caret)
```

# Load data from data_transformation.Rmd
```{r}
load(file = here("data", "model_data.Rdata"))
```


# GLM
```{r}
model_glm <- glm(LDLNTR ~  WHOLGR1N + REFGRA1N + BMISC + AGEC + SLPTIME + SYSTOL + EXLWTBC, family = "binomial", data = model_data)
summary(model_glm)

ctable <- coef(summary(model_glm))
p <- pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
ctable <- cbind(ctable, "p value" = Pr(>|z|))
ctable


```

# LDLRESB
## ordinal
```{r}

ordinal_1 <- polr(LDLRESB ~ WHOLGR1N + REFGRA1N + BMISC + AGEC + SLPTIME + SYSTOL + EXLWTBC, data = model_data)
summary(ordinal_1)
ctable <- coef(summary(ordinal_1))
p <- pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
ctable <- cbind(ctable, "p value" = p)
ctable
```


## multinomial
```{r}
nom_nom_1 <- multinom(LDLRESB ~ WHOLGR1N + REFGRA1N + BMISC + AGEC + SLPTIME + SYSTOL + EXLWTBC, data = model_data, trace=FALSE)
summary(nom_nom_1)

coef(summary(nom_nom_1))

# calculate p-values
zvalues <- summary(nom_nom_1)$coefficients / summary(nom_nom_1)$standard.errors
pnorm(abs(zvalues), lower.tail=FALSE)*2

```


## RF
## Kieran: didn't finish fixing this since we're not using it in the presentation
```{r}
model_data$LDLRESB_NUM <- as.numeric(model_data$LDLRESB)

classes <-  c(merged_data$LDLRESB)

breaks <- c(-Inf, 2, 5, 8)

label <- c("Ridiculous", "Ludicrous", "Plaid")

merged_data$grouped_LDLRESB <- cut(merged_data$LDLRESB, breaks = breaks, labels = label)

train_indices <- sample(1:nrow(merged_data), 0.8 * nrow(merged_data)) 
train_data <- merged_data[train_indices, ]
test_data <- merged_data[-train_indices, ]

forest_gump <- randomForest(grouped_LDLRESB ~ WHOLGR1N + REFGRA1N + BMISC + AGEC + SLPTIME + SYSTOL, data = train_data, ntree = 500, importance = TRUE)
predictions <- predict(forest_gump, newdata = test_data)

forest_gump
```


```{r}
varImpPlot(forest_gump, main="Model Performance Predicting LDLRESB Response")
```


# LDLNTR
## multinomial
```{r}
nom_nom_2 <- multinom(LDLNTR ~ WHOLGR1N + REFGRA1N + BMISC + AGEC + SLPTIME + SYSTOL + EXLWTBC + HDLCHREB + CHOLRESB, data = model_data, trace=FALSE)
summary(nom_nom_2)

zvalues <- summary(nom_nom_2)$coefficients / summary(nom_nom_2)$standard.errors

# calculate p-values
pnorm(abs(zvalues), lower.tail=FALSE)*2
```

## RF
```{r}
forest_gump_sequel <- randomForest(LDLNTR ~ WHOLGR1N + WHOLGR1N_PROP + REFGRA1N + BMISC + AGEC + SLPTIME + SYSTOL, data = train_data, ntree = 500, importance = TRUE)
predictions <- predict(forest_gump_sequel, newdata = test_data)

forest_gump_sequel
```

```{r}
varImpPlot(forest_gump_sequel, main="Model Performance Predicting LDLNTR Response")
```



# HDLCHREB

## ordinal
```{r}

ordinal_3 <- polr(LDLRESB ~ WHOLGR1N + REFGRA1N + BMISC + AGEC + SLPTIME + SYSTOL + EXLWTBC + HDLCHREB, data = model_data)
summary(ordinal_3)
ctable <- coef(summary(ordinal_3))
p <- pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
ctable <- cbind(ctable, "p value" = p)
ctable
```


## multinomial on HDLCHREB
```{r}
nom_nom_3 <- multinom(LDLRESB ~ WHOLGR1N  + REFGRA1N + BMISC + AGEC + SLPTIME + SYSTOL + EXLWTBC + HDLCHREB, data = model_data, trace=FALSE)
summary(nom_nom_3)

# calculate p-values
zvalues <- summary(nom_nom_3)$coefficients / summary(nom_nom_3)$standard.errors
pnorm(abs(zvalues), lower.tail=FALSE)*2
```

## RF

```{r}
train_indices_1 <- sample(1:nrow(model_data), 0.8 * nrow(model_data)) 
train_data_1 <- model_data[train_indices_1, ]
test_data_1 <- model_data[-train_indices_1, ]

forest_gump_trilogy <- randomForest(LDLRESB ~ WHOLGR1N + REFGRA1N + BMISC + AGEC + SLPTIME + SYSTOL + EXLWTBC + HDLCHREB, data = train_data_1, ntree = 500, importance = TRUE)
predictions <- predict(forest_gump_trilogy, newdata = test_data_1)

forest_gump_trilogy
```


# CHOLRESB
## ordinal

```{r}
ordinal_4 <- polr(CHOLRESB ~ WHOLGR1N + REFGRA1N + BMISC + AGEC + SLPTIME + SYSTOL + EXLWTBC + HDLCHREB, data = model_data)
summary(ordinal_4)
ctable <- coef(summary(ordinal_4))
p <- pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
ctable <- cbind(ctable, "p value" = p)
ctable
```

